[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
onnyx_advertise = "GJ6EXCbn3BNRwvRAATBXwJKU3cCv8ScQC7FyxF82vShP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
